/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282115
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        ButtonSair = new javax.swing.JButton();
        ButtonAgenda = new javax.swing.JButton();
        ButtonPacientes = new javax.swing.JButton();
        ButtonMedicos = new javax.swing.JButton();
        ButtonEspecialidades = new javax.swing.JButton();
        ButtonPlanosDeSaude = new javax.swing.JButton();
        PanelPlanoDeSaude = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonEspecialidades1 = new javax.swing.JButton();
        ButtonEspecialidades2 = new javax.swing.JButton();
        ButtonEspecialidades3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento de Consultas");
        setBackground(new java.awt.Color(242, 242, 241));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tituloLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 153, 255));
        tituloLabel.setText("Sistema de Agendamento de Consultas");
        jPanel2.add(tituloLabel);
        tituloLabel.setBounds(90, 10, 660, 70);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/agendar.png"))); // NOI18N
        jPanel2.add(iconLabel);
        iconLabel.setBounds(10, 10, 70, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 940, 90);

        ButtonSair.setForeground(new java.awt.Color(255, 51, 51));
        ButtonSair.setText("Sair");
        ButtonSair.setBorder(null);
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSair);
        ButtonSair.setBounds(840, 100, 90, 40);

        ButtonAgenda.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ButtonAgenda.setText("Agenda");
        ButtonAgenda.setBorder(null);
        ButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAgenda);
        ButtonAgenda.setBounds(30, 100, 130, 40);

        ButtonPacientes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ButtonPacientes.setText("Pacientes");
        ButtonPacientes.setBorder(null);
        ButtonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPacientes);
        ButtonPacientes.setBounds(170, 100, 130, 40);

        ButtonMedicos.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ButtonMedicos.setText("Médicos");
        ButtonMedicos.setBorder(null);
        ButtonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMedicos);
        ButtonMedicos.setBounds(310, 100, 130, 40);

        ButtonEspecialidades.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ButtonEspecialidades.setText("Especialidades");
        ButtonEspecialidades.setBorder(null);
        ButtonEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEspecialidades);
        ButtonEspecialidades.setBounds(450, 100, 130, 40);

        ButtonPlanosDeSaude.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ButtonPlanosDeSaude.setForeground(new java.awt.Color(0, 51, 255));
        ButtonPlanosDeSaude.setText("Planos de Saúde");
        ButtonPlanosDeSaude.setBorder(null);
        ButtonPlanosDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlanosDeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlanosDeSaude);
        ButtonPlanosDeSaude.setBounds(590, 100, 130, 40);

        PanelPlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Planos de Saúde:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        PanelPlanoDeSaude.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PanelPlanoDeSaude.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 870, 290);

        ButtonEspecialidades1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ButtonEspecialidades1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/edit.png"))); // NOI18N
        ButtonEspecialidades1.setToolTipText("editar plano de saúde selecionado ");
        ButtonEspecialidades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEspecialidades1ActionPerformed(evt);
            }
        });
        PanelPlanoDeSaude.add(ButtonEspecialidades1);
        ButtonEspecialidades1.setBounds(780, 330, 40, 40);

        ButtonEspecialidades2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ButtonEspecialidades2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/add.png"))); // NOI18N
        ButtonEspecialidades2.setToolTipText("adicionar plano de saúde");
        ButtonEspecialidades2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEspecialidades2ActionPerformed(evt);
            }
        });
        PanelPlanoDeSaude.add(ButtonEspecialidades2);
        ButtonEspecialidades2.setBounds(830, 330, 40, 40);

        ButtonEspecialidades3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ButtonEspecialidades3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/delete.png"))); // NOI18N
        ButtonEspecialidades3.setToolTipText("deletar plano de saúde selecionado");
        ButtonEspecialidades3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEspecialidades3ActionPerformed(evt);
            }
        });
        PanelPlanoDeSaude.add(ButtonEspecialidades3);
        ButtonEspecialidades3.setBounds(730, 330, 40, 40);

        getContentPane().add(PanelPlanoDeSaude);
        PanelPlanoDeSaude.setBounds(30, 170, 890, 390);

        setBounds(0, 0, 955, 598);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAgendaActionPerformed

    private void ButtonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPacientesActionPerformed

    private void ButtonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMedicosActionPerformed

    private void ButtonEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEspecialidadesActionPerformed

    private void ButtonPlanosDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlanosDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPlanosDeSaudeActionPerformed

    private void ButtonEspecialidades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEspecialidades1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEspecialidades1ActionPerformed

    private void ButtonEspecialidades2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEspecialidades2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEspecialidades2ActionPerformed

    private void ButtonEspecialidades3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEspecialidades3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEspecialidades3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgenda;
    private javax.swing.JButton ButtonEspecialidades;
    private javax.swing.JButton ButtonEspecialidades1;
    private javax.swing.JButton ButtonEspecialidades2;
    private javax.swing.JButton ButtonEspecialidades3;
    private javax.swing.JButton ButtonMedicos;
    private javax.swing.JButton ButtonPacientes;
    private javax.swing.JButton ButtonPlanosDeSaude;
    private javax.swing.JButton ButtonSair;
    private javax.swing.JPanel PanelPlanoDeSaude;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
