/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import javax.imageio.plugins.jpeg.JPEGQTable;
import javax.swing.JTable;

/**
 *
 * @author 22282115
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        PlanoDeSaudeDAO.criarPlanosDeSaudeTeste();
        criarTabelaPlanosDeSaude();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        buttonAgenda = new javax.swing.JButton();
        buttonPacientes = new javax.swing.JButton();
        buttonMedicos = new javax.swing.JButton();
        buttonEspecialidades = new javax.swing.JButton();
        buttonPlanosDeSaude = new javax.swing.JButton();
        panelPlanoDeSaude = new javax.swing.JPanel();
        scrollPanePlanosDeSaude = new javax.swing.JScrollPane();
        tablePlanosDeSaude = new javax.swing.JTable();
        buttonEditar = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento de Consultas");
        setBackground(new java.awt.Color(242, 242, 241));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tituloLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 153, 255));
        tituloLabel.setText("Sistema de Agendamento de Consultas");
        jPanel2.add(tituloLabel);
        tituloLabel.setBounds(90, 10, 660, 70);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/agendar.png"))); // NOI18N
        jPanel2.add(iconLabel);
        iconLabel.setBounds(10, 10, 70, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 940, 90);

        buttonSair.setForeground(new java.awt.Color(255, 51, 51));
        buttonSair.setText("Sair");
        buttonSair.setBorder(null);
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSair);
        buttonSair.setBounds(840, 100, 90, 40);

        buttonAgenda.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        buttonAgenda.setText("Agenda");
        buttonAgenda.setBorder(null);
        buttonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgenda);
        buttonAgenda.setBounds(30, 100, 130, 40);

        buttonPacientes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        buttonPacientes.setText("Pacientes");
        buttonPacientes.setToolTipText("");
        buttonPacientes.setBorder(null);
        buttonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPacientes);
        buttonPacientes.setBounds(170, 100, 130, 40);

        buttonMedicos.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        buttonMedicos.setText("Médicos");
        buttonMedicos.setBorder(null);
        buttonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMedicos);
        buttonMedicos.setBounds(310, 100, 130, 40);

        buttonEspecialidades.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        buttonEspecialidades.setText("Especialidades");
        buttonEspecialidades.setBorder(null);
        buttonEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEspecialidades);
        buttonEspecialidades.setBounds(450, 100, 130, 40);

        buttonPlanosDeSaude.setBackground(new java.awt.Color(234, 255, 255));
        buttonPlanosDeSaude.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        buttonPlanosDeSaude.setForeground(new java.awt.Color(0, 51, 255));
        buttonPlanosDeSaude.setText("Planos de Saúde");
        buttonPlanosDeSaude.setBorder(null);
        buttonPlanosDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanosDeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlanosDeSaude);
        buttonPlanosDeSaude.setBounds(590, 100, 130, 40);

        panelPlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Planos de Saúde:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        panelPlanoDeSaude.setLayout(null);

        tablePlanosDeSaude.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tablePlanosDeSaude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePlanosDeSaude.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        scrollPanePlanosDeSaude.setViewportView(tablePlanosDeSaude);

        panelPlanoDeSaude.add(scrollPanePlanosDeSaude);
        scrollPanePlanosDeSaude.setBounds(10, 30, 870, 290);

        buttonEditar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/edit.png"))); // NOI18N
        buttonEditar.setToolTipText("editar plano de saúde selecionado ");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonEditar);
        buttonEditar.setBounds(780, 330, 40, 40);

        buttonAdicionar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        buttonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/add.png"))); // NOI18N
        buttonAdicionar.setToolTipText("adicionar plano de saúde");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonAdicionar);
        buttonAdicionar.setBounds(830, 330, 40, 40);

        buttonExcluir.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        buttonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/delete.png"))); // NOI18N
        buttonExcluir.setToolTipText("deletar plano de saúde selecionado");
        buttonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonExcluir);
        buttonExcluir.setBounds(730, 330, 40, 40);

        getContentPane().add(panelPlanoDeSaude);
        panelPlanoDeSaude.setBounds(30, 170, 890, 390);

        setBounds(0, 0, 955, 598);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgendaActionPerformed

    private void buttonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPacientesActionPerformed

    private void buttonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMedicosActionPerformed

    private void buttonEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEspecialidadesActionPerformed

    private void buttonPlanosDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanosDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanosDeSaudeActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExcluirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonAgenda;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEspecialidades;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonMedicos;
    private javax.swing.JButton buttonPacientes;
    private javax.swing.JButton buttonPlanosDeSaude;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPlanoDeSaude;
    private javax.swing.JScrollPane scrollPanePlanosDeSaude;
    private javax.swing.JTable tablePlanosDeSaude;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    private void criarTabelaPlanosDeSaude() {
       tablePlanosDeSaude.setModel(PlanoDeSaudeDAO.getTableModel());
       
       // Desativar
       tablePlanosDeSaude.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       
       // Definir a largura de cada coluna
       tablePlanosDeSaude.getColumnModel().getColumn(0).setPreferredWidth(100);
       tablePlanosDeSaude.getColumnModel().getColumn(1).setPreferredWidth(400);
       tablePlanosDeSaude.getColumnModel().getColumn(2).setPreferredWidth(367);
       
       //impedir movimentação da coluna
       tablePlanosDeSaude.getTableHeader().setReorderingAllowed(false);
       
       //impedir edição das linhas
       tablePlanosDeSaude.setDefaultEditor(Object.class, null);
       
       
    }
}
